language: python
python:
  - "3.5"
  - "3.6"
install: 
  - pip3 install -r requirements.txt
  - pip3 install codecov
script: 
  - python3 -m pytest tests --cov app --cov-report html
  - coverage run -m pytest tests --cov app --cov-report html
after_success:
  - codecov
