language: python
python:
  - "3.5"
  - "3.6"
branches:
  only:
    - master
    - cc_badge
notifications:
  email: false
install: 
  - pip3 install -r requirements.txt
  - pip3 install codecov
script: 
  - coverage run -m pytest tests --cov meetup_facebook_bot
after_success:
  - coverall
