language: python
python:
  - "3.5"
  - "3.6"
notifications:
  email: false
install: 
  - pip3 install -r requirements.txt
  - pip3 install coveralls
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
script: 
  - python3 -m pytest tests --cov meetup_facebook_bot
after_success:
  - coveralls
